[build]
publish = "."
command = ""

[functions]
node_bundler = "esbuild"

[functions."*"]
external_node_modules = ["netlify:blobs"]

[functions.environment]
NETLIFY_USE_NODE_20 = "true"



