[build]
publish = "."
command = ""
environment = { NODE_VERSION = "18" }

[functions]
directory = "netlify/functions"

[functions."pre-generate"]
schedule = "0 6 * * *"

[functions."pre-generate-b"]
schedule = "5 6 * * *"

[functions."pre-generate-c"]
schedule = "10 6 * * *"



