[build]
publish = "."
command = ""
environment = { NODE_VERSION = "18" }

[functions]
directory = "netlify/functions"

# CRON A (6 signs)
[functions."pre-generate"]
schedule = "@daily"

# CRON B (6 signs)
[functions."pre-generate-b"]
schedule = "@daily"

